= Echo + Swagger

This is my first try with Echo & Swagger


== Run Test
    cd backend
    go test tests/ -count=1


== Run the API backend
The commands below generate swagger documentation and run the server.

    cd backend
    swag init -g main.go && APPLICATION_CLIENT_ID=<google-client-id> go run main.go

Go to the web browser and open: `http://localhost:8080`

Notes:

* The google-client-id (or OAuth 2.0 Client ID) must be registered on https://console.developers.google.com/
* In the Credentials section, the Authorised JavaScript origins must be set to http://localhost:8080 or your FQDN on which the web app is deployed.

== Use Docker

Create `./backend/config/backend-variables.env` based on the template `./backend/config/backend-variables.env.in`

To build the image and start the container, run the following command:

    docker-compose build
    docker-compose up


To stop and delete the container, run the following command:

    docker-compose down


== API

|===
| Resource Path      | Description

| swagger/index.html | Open the API documentation
| login              | Ask the user to sign-in using google (front end)
| auth (POST)        | Authenticate with an id token (back end).
                       It is called automatically after a successful login.